import { useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { X, Mail, Lock, User, Gift, Eye, EyeOff } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";

interface AuthModalProps {
  open: boolean;
  onClose: () => void;
}

const AuthModal = ({ open, onClose }: AuthModalProps) => {
  const { signUp, signIn } = useAuth();
  const [mode, setMode] = useState<"login" | "register">("register");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [name, setName] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  const generatePassword = () => {
    const chars = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$";
    let pw = "";
    for (let i = 0; i < 12; i++) pw += chars[Math.floor(Math.random() * chars.length)];
    return pw;
  };

  const handleAutoRegister = async () => {
    if (!email.trim()) {
      toast.error("Bitte gib deine E-Mail-Adresse ein");
      return;
    }
    setLoading(true);
    const pw = generatePassword();
    const { error } = await signUp(email, pw, name || undefined);
    if (error) {
      if (error.message?.includes("already registered")) {
        toast.error("Diese E-Mail ist bereits registriert. Bitte melde dich an.");
        setMode("login");
      } else {
        toast.error(error.message || "Registrierung fehlgeschlagen");
      }
    } else {
      setPassword(pw);
      setAutoGenerated(true);
      toast.success("Konto erstellt! Dein Passwort wurde generiert.");
    }
    setLoading(false);
  };

  const handleLogin = async () => {
    if (!email.trim() || !password.trim()) {
      toast.error("Bitte fülle alle Felder aus");
      return;
    }
    setLoading(true);
    const { error } = await signIn(email, password);
    if (error) {
      toast.error("Login fehlgeschlagen. Prüfe deine Daten.");
    } else {
      toast.success("Erfolgreich eingeloggt!");
      onClose();
    }
    setLoading(false);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (mode === "register") handleAutoRegister();
    else handleLogin();
  };

  if (!open) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
        onClick={onClose}
      >
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          onClick={(e) => e.stopPropagation()}
          className="bg-card border border-border rounded-2xl p-6 w-full max-w-md shadow-2xl"
        >
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-2">
              <Gift className="w-5 h-5 text-accent" />
              <h2 className="font-display text-xl font-bold text-foreground">
                {mode === "register" ? "Punkte sammeln" : "Anmelden"}
              </h2>
            </div>
            <button onClick={onClose} className="text-muted-foreground hover:text-foreground">
              <X className="w-5 h-5" />
            </button>
          </div>

          {mode === "register" && !autoGenerated && (
            <p className="text-muted-foreground text-sm mb-5">
              Gib einfach deine E-Mail ein — wir erstellen automatisch ein Konto für dich und du sammelst ab sofort <span className="text-accent font-semibold">5 Punkte pro CHF</span>!
            </p>
          )}

          {autoGenerated ? (
            <div className="space-y-4">
              <div className="bg-accent/10 border border-accent/30 rounded-xl p-4 space-y-3">
                <p className="text-foreground font-semibold text-sm">🎉 Dein Konto wurde erstellt!</p>
                <p className="text-muted-foreground text-xs">Dein automatisch generiertes Passwort:</p>
                <div className="flex items-center gap-2 bg-background/50 rounded-lg p-3">
                  <code className="text-foreground font-mono text-sm flex-1">
                    {showPassword ? password : "••••••••••••"}
                  </code>
                  <button onClick={() => setShowPassword(!showPassword)} className="text-muted-foreground hover:text-foreground">
                    {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>
                <p className="text-muted-foreground text-xs">
                  Bitte notiere dir dieses Passwort. Du kannst es jederzeit in deinem Profil ändern.
                </p>
              </div>
              <button
                onClick={() => { onClose(); setAutoGenerated(false); }}
                className="w-full bg-accent text-accent-foreground py-3 rounded-xl font-semibold hover:opacity-90 transition-opacity"
              >
                Verstanden, los geht's!
              </button>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4">
              {mode === "register" && (
                <div>
                  <label className="block text-sm font-medium text-foreground mb-1.5">Name (optional)</label>
                  <div className="relative">
                    <User className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                    <input
                      type="text"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      className="w-full pl-10 pr-4 py-3 rounded-lg border border-border bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-accent"
                      placeholder="Dein Name"
                    />
                  </div>
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-foreground mb-1.5">E-Mail *</label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                  <input
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                    className="w-full pl-10 pr-4 py-3 rounded-lg border border-border bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-accent"
                    placeholder="deine@email.ch"
                  />
                </div>
              </div>

              {mode === "login" && (
                <div>
                  <label className="block text-sm font-medium text-foreground mb-1.5">Passwort</label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                    <input
                      type={showPassword ? "text" : "password"}
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      required
                      className="w-full pl-10 pr-10 py-3 rounded-lg border border-border bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-accent"
                      placeholder="Dein Passwort"
                    />
                    <button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                      {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    </button>
                  </div>
                </div>
              )}

              <button
                type="submit"
                disabled={loading}
                className="w-full bg-accent text-accent-foreground py-3 rounded-xl font-semibold hover:opacity-90 transition-opacity disabled:opacity-60"
              >
                {loading ? "Wird verarbeitet..." : mode === "register" ? "Konto erstellen & Punkte sammeln" : "Anmelden"}
              </button>

              <button
                type="button"
                onClick={() => { setMode(mode === "login" ? "register" : "login"); setAutoGenerated(false); }}
                className="w-full text-center text-sm text-muted-foreground hover:text-foreground transition-colors"
              >
                {mode === "login" ? "Noch kein Konto? Jetzt registrieren" : "Bereits ein Konto? Anmelden"}
              </button>
            </form>
          )}
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
};

export default AuthModal;
